#+title: 2.5 Exercises

* Exercise 2.77
Louis Reasoner tries to evaluate the expression (magnitude z) where z is the object shown in Figure 2.24.  To his surprise, instead of the answer 5 he gets an error message from apply-generic, saying there is no method for the operation magnitude on the types (complex).  He shows this interaction to Alyssa P. Hacker, who says "The problem is that the complex-number selectors were never defined for complex numbers, just for polar and rectangular numbers.  All you have to do to make this work is add the following to the complex package:"

#+begin_src scheme :eval never
(put 'real-part '(complex) real-part)
(put 'imag-part '(complex) imag-part)
(put 'magnitude '(complex) magnitude)
(put 'angle '(complex) angle)
#+end_src

Describe in detail why this works.  As an example, trace through all the procedures called in evaluating the expression (magnitude z) where z is the object shown in Figure 2.24.  In particular, how many times is apply-generic invoked?  What procedure is dispatched to in each case?

** Solution
The structure of z is '(complex rectangular 3 . 4), so the type-tag of z is 'complex. The definition of magnitude is:
#+begin_src scheme :eval never
(define (magnitude z)
  (apply-generic 'magnitude z))
#+end_src
Thus when magnitude is called for z it will apply magnitude again to the contents of z, that is '(rectangular 3 . 4). Now, magnitude will apply-generic again to an object which its type-tag is 'rectangular, and then magnitude defined in the rectangular package will be applied to 3 . 4.

* Exercise 2.78
The internal procedures in the scheme-number package are essentially nothing more than calls to the primitive procedures +, -, etc.  It was not possible to use the primitives of the language directly because our type-tag system requires that each data object have a type attached to it.  In fact, however, all Lisp implementations do have a type system, which they use internally.  Primitive predicates such as symbol? and number?  determine whether data objects have particular types.  Modify the definitions of type-tag, contents, and attach-tag from 2.4.2 so that our generic system takes advantage of Scheme's internal type system.  That is to say, the system should work as before except that ordinary numbers should be represented simply as Scheme numbers rather than as pairs whose car is the symbol scheme-number.

** Solution
#+begin_src scheme
(define (attach-tag type-tag contents)
  (if (eq? type-tag 'scheme-number)
      contents
      (cons type-tag contents)))

(define (type-tag datum)
  (cond ((number? datum) 'scheme-number)
        ((pair? datum)
         (car datum))
        (else
         (error "Bad tagged datum: TYPE-TAG"
                datum))))

(define (contents datum)
  (cond ((number? datum) datum)
        ((pair? datum)
         (cdr datum))
        (else
         (error "Bad tagged datum: CONTENTS"
                datum))))
#+end_src

* Exercise 2.79
Define a generic equality predicate equ? that tests the equality of two numbers, and install it in the generic arithmetic package.  This operation should work for ordinary numbers, rational numbers, and complex numbers.

** Solution
#+begin_src scheme
(define (install-equality-package)
  (put 'equ?
       '(scheme-number scheme-number)
       (lambda (x y)
         (= x y)))
  (put 'equ?
       '(rational rational)
       (lambda (x y)
         (and (= (numerator x) (numerator y))
              (= (denominator x) (denominator y)))))
  (put 'equ?
       '(complex complex)
       (lambda (x y)
         (and (= (real-part x) (real-part y))
              (= (imag-part x) (imag-part y)))))
  'done)

(define (equ? x y)
  (apply-generic 'equ? x y))
#+end_src

* Exercise 2.80
Define a generic predicate =zero? that tests if its argument is zero, and install it in the generic arithmetic package.  This operation should work for ordinary numbers, rational numbers, and complex numbers.

** Solution
#+begin_src scheme
(define (install-zero-predicate-package)
  (put '=zero?
       '(scheme-number)
       (lambda (x)
         (= 0 x)))
  (put '=zero?
       '(rational)
       (lambda (x)
         (= 0 (numerator x))))
  (put '=zero?
       '(complex)
       (lambda (x)
         (and (= 0 (real-part x))
              (= 0 (imag-part x)))))
  'done)

(define (=zero? x)
  (apply-generic '=zero? x))
#+end_src

* TODO Exercise 2.81
Louis Reasoner has noticed that apply-generic may try to coerce the arguments to each other’s type even if they already have the same type.  Therefore, he reasons, we need to put procedures in the coercion table to coerce arguments of each type to their own type.  For example, in addition to the scheme-number->complex coercion shown above, he would do:

#+begin_src scheme :eval never
(define (scheme-number->scheme-number n) n)
(define (complex->complex z) z)

(put-coercion 'scheme-number 'scheme-number
              scheme-number->scheme-number)

(put-coercion 'complex 'complex
              complex->complex)
#+end_src

1. With Louis’s coercion procedures installed, what happens if apply-generic is called with two arguments of type scheme-number or two arguments of type complex for an operation that is not found in the table for those types?  For example, assume that we’ve defined a generic exponentiation operation:

#+begin_src scheme :eval never
(define (exp x y)
  (apply-generic 'exp x y))
#+end_src

and have put a procedure for exponentiation in the Scheme-number package but not in any other package:

#+begin_src scheme :eval never
;; following added to Scheme-number package
(put 'exp
     '(scheme-number scheme-number)
     (lambda (x y)
       (tag (expt x y))))
       ; using primitive expt
#+end_src

What happens if we call exp with two complex numbers as arguments?

2. Is Louis correct that something had to be done about coercion with arguments of the same type, or does apply-generic work correctly as is?

3. Modify apply-generic so that it doesn’t try coercion if the two arguments have the same type.

* TODO Exercise 2.82
Show how to generalize apply-generic to handle coercion in the general case of multiple arguments.  One strategy is to attempt to coerce all the arguments to the type of the first argument, then to the type of the second argument, and so on. Give an example of a situation where this strategy (and likewise the two-argument version given above) is not sufficiently general.  (Hint: Consider the case where there are some suitable mixed-type operations present in the table that will not be tried.)
