#+TITLE: 1.1 Example: Square Roots by Newton's Method

* Exercise 1.6
Alyssa P. Hacker doesn't see why if needs to be provided as a special form. “Why can’t I just define it as an ordinary procedure in terms of cond?” she asks. Alyssa’s friend Eva Lu Ator claims this can indeed be done, and she defines a new version of if:

#+begin_src scheme :eval never
(define (new-if predicate
                then-clause
                else-clause)
  (cond (predicate 'then-clause)
        (else 'else-clause)))

(define (sqrt-iter guess x)
  (new-if (good-enough? guess x)
          guess
          (sqrt-iter (improve guess x) x)))
#+end_src

Eva demonstrates the program for Alyssa:
#+begin_example
> (new-if (= 2 3) 0 5)
$1 = 5

> (new-if (= 1 1) 0 5)
$2 = 0
#+end_example

Delighted, Alyssa uses new-if to rewrite the square-root program:
#+begin_src scheme :eval never
(define (sqrt-iter guess x)
  (new-if (good-enough? guess x)
          guess
          (sqrt-iter (improve guess x) x)))
#+end_src

What happens when Alyssa attempts to use this to compute square roots? Explain.

** Solution
As new-if is a regular procedure, so, it's arguments get evaluated first and that leads to a infinite recursion of sqrt-iter. The special form if, on the other hand, evaluate the consequent only if the predicate is true, the alternative get evaluated only if otherwise.

* Exercise 1.7
The good-enough? test used in computing square roots will not be very effective for finding the square roots of very small numbers. Also, in real computers, arithmetic operations are almost always performed with limited precision. This makes our test inadequate for very large numbers. Explain these statements, with examples showing how the test fails for small and large numbers. An alternative strategy for implementing good-enough? is to watch how guess changes from one iteration to the next and to stop when the change is a very small fraction of the guess. Design a square-root procedure that uses this kind of end test. Does this work better for small and large numbers?

** Solution
#+begin_src scheme
(define (good-enough? last-guess guess)
  (< (abs (- 1 (/ last-guess guess))) 0.001))

(define (improve guess x)
  (/ (+ guess (/ x guess)) 2))

(define (sqrt-iter x last-guess guess)
  (if (good-enough? last-guess guess)
      guess
      (sqrt-iter x guess (improve guess x))))

(define (sqrt x)
  (sqrt-iter x 0.0 1.0))

(test-approximate 100000.0 (sqrt 10000000000.0) 0.001)
#+end_src

* Exercise 1.8
Newton’s method for cube roots is based on the fact that if y is an approximation to the cube root of x, then a better approximation is given by the value:

\[ \frac{x/y^2 + 2y}{3} \]

Use this formula to implement a cube-root procedure analogous to the square-root procedure. (In 1.3.4 we will see how to implement Newton’s method in general as an abstraction of these square-root and cube-root procedures.)

** Solution
#+begin_src scheme
(define (good-enough? last-guess guess)
  (< (abs (- 1 (/ last-guess guess))) 0.001))

(define (improve-cube-root-guess y x)
  (/ (+ (/ x (* y y)) (* 2 y)) 3))

(define (cube-root-iter x last-guess guess)
  (if (good-enough? last-guess guess)
      guess
      (cube-root-iter x guess (improve-cube-root-guess guess x))))

(define (cube-root x)
  (cube-root-iter x 0.0 1.0))

(test-approximate 3 (cube-root 27) 0.001)
#+end_src
